[package]
name = "translate-platform-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio-postgres = "0.7.10"
postgresql_embedded = { version = "0.9.2", features = ["tokio"] }
tokio = { version = "1.37.0", features = ["full"] }               # async networking
