[config]
default_to_workspace = false
skip_core_tasks = true

[tasks.init-db]
script = '''
#!@duckscript

exec docker run --name kongying-db -e MARIADB_USER=kongying -e MARIADB_PASSWORD=HoM0iI45l4L9198iO -e MARIADB_DATABASE=kongying -e MARIADB_RANDOM_ROOT_PASSWORD=yes -p 3306:3306 -d mariadb:lts
exec docker start kongying-db
'''

[tasks.lint]
script = '''
#!@duckscript

exec cargo check --all-targets --all-features
exec cargo clippy --all-targets --all-features -- -D warnings
'''

[tasks.dev]
script = '''
#!@duckscript

set_env PORT 8080
set_env JWT_SECRET "test.kongying-tavern"
exec cargo run --package _boot
'''

[tasks.watch]
watch = { watch = ["./packages/"] }
run_task = { name = ["dev"], fork = true }

[tasks.run]
script = '''
#!@duckscript

exec docker build -t kongying-tavern-boot .
exec docker-compose -f Compose.yml up -d
'''

[tasks.publish]
script = '''
#!@duckscript

exec docker build -t kongying-tavern-boot .
exec docker tag kongying-tavern-boot:latest registry.cn-shanghai.aliyuncs.com/langyo/kongying-tavern-boot:latest
exec docker push registry.cn-shanghai.aliyuncs.com/langyo/kongying-tavern-boot:latest
'''
