[tasks.default]
alias = "help"

[tasks.dataenv] # ? Data environment
script = '''
#!@duckscript
'''

# help
[tasks.help]
script = '''
#!@duckscript
!include_files ./util/env.ds
!include_files ./util/help.ds

# Get env
prepare_env_vars
check_env

# Print help
print_banner ./makefile/banner.txt
print_env_path "Current env file"
cmds = get_help_commands "?" ">"
print_help_commands ${cmds} 30 "Available commands"
get_command_input "What do you want?"

release ${cmds}
'''
