[tasks.default]
alias = "help"

[tasks.dataenv] # ? Data environment
script = '''
#!@duckscript
!include_files ./util/index.ds
prepare_env_vars
a = get_env "ENV_FILE"
extract_env_vars
check_env_file

docker_build "${ENV_FILE}" "${PROJECT_NAME}" "./composer/dataenv.build.yml"
# docker_down "${ENV_FILE}" "${PROJECT_NAME}" "./composer/dataenv.yml"
# docker_up "${ENV_FILE}" "${PROJECT_NAME}" "./composer/dataenv.yml"
'''

# help
[tasks.help]
script = '''
#!@duckscript
!include_files ./util/index.ds
prepare_env_vars
check_env_file

# Print help
print_banner ./makefile/banner.txt
print_env_path "Current env file"
cmds = get_help_cmds "?" ">"
print_help_cmds ${cmds} 30 "Available commands"
get_cmd_input "What do you want?"

release ${cmds}
'''
