[config]
default_to_workspace = false
skip_core_tasks = true
reduce_output = false

[tasks.default]
description = "开发环境启动"
dependencies = [
    "check",
    "docker",
]
script = '''
echo ""
echo "🎉 开发环境启动!"
'''

[tasks.check]
description = "全面系统检查"
cwd = "../"
command = "makers"
args = ["--makefile", "Makefile.toml", "check", "--quiet"]

[tasks.docker]
description = "启动Docker容器"
cwd = "../"
script = """
echo "🐳  启动Docker容器..."

if docker compose up -d; then
    :
else
    echo "docker compose 启动失败，可以考虑运行 'cargo make check [docker]' 进行检查。"
fi
"""